version: "3.1"
services:
  garrysmod:
    container_name: garrysmod          
    build: .
    ports:
      - "27005:27005/udp"
      - "27015:27015/udp"
    volumes:
      - ./server.cfg:/home/steam/gmodds/garrysmod/cfg/server.cfg
      - ./users.txt:/home/steam/gmodds/garrysmod/settings/users.txt
      - garrysmod-gmas:/home/steam/gmodds/garrysmod/cache/srcds/
      - garrysmod-addons:/home/steam/gmodds/garrysmod/addons/
      - garrysmod-data:/home/steam/gmodds/garrysmod/data/
    stdin_open: true               
    tty: true
    command: +gamemode terrortown +map ttt_lego +host_workshop_collection 716717312
volumes:
  garrysmod-gmas:
  garrysmod-addons:
  garrysmod-data:
